"""Add Feedback table

Revision ID: 1005d89c9cc7
Revises: 11a84316f7f0
Create Date: 2026-08-20 07:44:55.568169

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1005d89c9cc7'
down_revision: Union[str, Sequence[str], None] = '11a84316f7f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedbacks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('canvas_id', sa.String(length=36), nullable=False),
    sa.Column('founder_strengths', sa.Text(), nullable=False),
    sa.Column('execution_gaps', sa.Text(), nullable=False),
    sa.Column('recommended_actions', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['canvas_id'], ['canvases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canvas_id')
    )
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedbacks_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedbacks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedbacks_id'))

    op.drop_table('feedbacks')
    # ### end Alembic commands ###
