"""create canvases table and relationships in users and ideas 

Revision ID: 11a84316f7f0
Revises: 5f5947b2e2b5
Create Date: 2026-08-19 07:48:48.409534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11a84316f7f0'
down_revision: Union[str, Sequence[str], None] = '5f5947b2e2b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canvases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('idea_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('customer_segments', sa.Text(), nullable=True),
    sa.Column('value_propositions', sa.Text(), nullable=True),
    sa.Column('channels', sa.Text(), nullable=True),
    sa.Column('customer_relationships', sa.Text(), nullable=True),
    sa.Column('revenue_streams', sa.Text(), nullable=True),
    sa.Column('key_resources', sa.Text(), nullable=True),
    sa.Column('key_activities', sa.Text(), nullable=True),
    sa.Column('key_partnerships', sa.Text(), nullable=True),
    sa.Column('cost_structure', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['idea_id'], ['ideas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('canvases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_canvases_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvases_idea_id'), ['idea_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_canvases_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('canvases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_canvases_user_id'))
        batch_op.drop_index(batch_op.f('ix_canvases_idea_id'))
        batch_op.drop_index(batch_op.f('ix_canvases_id'))

    op.drop_table('canvases')
    # ### end Alembic commands ###
