"""Change DateTime to UTCDateTime

Revision ID: 42b2abbf741d
Revises: 1005d89c9cc7
Create Date: 2026-08-25 13:33:23.861491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42b2abbf741d'
down_revision: Union[str, Sequence[str], None] = '1005d89c9cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
