"""Add unique constraint

Revision ID: 5f5947b2e2b5
Revises: d599276b99c7
Create Date: 2026-08-19 06:52:08.214812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f5947b2e2b5'
down_revision: Union[str, Sequence[str], None] = 'd599276b99c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_user_idea_title', ['user_id', 'title'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ideas', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_idea_title', type_='unique')

    # ### end Alembic commands ###
